platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3-jdk-8-alpine

inputs:
  - name: android-bff

outputs:
  - name: build-targets
    path: android-bff-service/target

run:
  path: mvn
  args: [package]
  dir: ./android-bff
