---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
  - name: android-bff
    type: git
    source:
      uri: ssh://git@188.166.155.119:2222/Nedbank/pwealth-android-bff.git
      branch: master
      skip_ssl_checking: true
      private_key: {{DEPLOY_KEY}}

  - name: notify-slack
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/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

jobs:
  - name: build-bff
    plan:
      - get: android-bff
        trigger: true
      - task: build
        file: android-bff/ci/build.yml
      - put: notify-slack
        params:
          text: |
            android-bff build completed. View the result at:
            http://139.59.197.102:8080/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
